### ISSUE TITLE
Unsupported type 'year' for driver 'mysql'

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#499]
As reported on closed issue #431

**Comment by luisrock** [comment]
Thanks for that, man.

**Comment by mevdschee** [comment]
yeah.. I guess the problem is that the generator does not know what to do with a year type (not specified in openapi). The solution is to adjust the code to fallback to integer for this type.

**Comment by luisrock** [comment]
hum...can I have a step by step action list? I really don't have a clue...

**Comment by mevdschee** [comment]
Sure, just download the 'api.php' from the latest master with my changes and try again :-)

**Comment by luisrock** [comment]
Wow. Thank you for that, man!

**Comment by mevdschee** [comment]
Does it work for you? Please let me know.

**Comment by luisrock** [comment]
Well, I must be doing something wrong. I created a folder ('api') and uploaded the api file ('api.php') to it. When a I visit `mysite.com/api/api.php`, I get 

`HTTP/1.1 404 Not Found
Server: nginx/1.13.3
Date: Tue, 19 Feb 2019 09:51:45 GMT
Content-Type: application/json
Content-Length: 46
Connection: close

{"code":1000,"message":"Route '\/' not found"}`

Ok, that means my db was reached (because if I set wrong credentials, I don' get that).

But if I put a slash after that, like `mysite.com/api/api.php/`, I get...my website's homepage (index.html). Thus, when I go to `mysite.com/api/api.php/records/as_users` (expecting to see a list of users), I get homepage again.

So, `mysite.com/api/api.php/openapi` is showing me my homepage.

Any advice?

**Comment by mevdschee** [comment]
>Any advice?

Yes, you are not having $_SERVER['PATH_INFO'] set to the right value due to misconfiguration of nginx.

See: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by luisrock** [comment]
My server is managed by Laravel Forge. Do you think they something to do
with that misconfiguration?

Em ter, 19 de fev de 2019 às 09:40, Maurits van der Schee <
notifications@github.com> escreveu:

**Comment by mevdschee** [comment]
>Do you think they something to do with that misconfiguration?

Yes, they seem not to pass the PATH_INFO server variable or not match the PHP file in a recommended way.

**Comment by luisrock** [comment]
Ok, but first, can you see where is the problem?

    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/admin.zeraedital.com.br/before/*;

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name admin.zeraedital.com.br;
        root /home/forge/admin.zeraedital.com.br/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/admin.zeraedital.com.br/271160/server.crt;
    ssl_certificate_key /etc/nginx/ssl/admin.zeraedital.com.br/271160/server.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!3DES';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/admin.zeraedital.com.br/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/admin.zeraedital.com.br-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
    }

    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/admin.zeraedital.com.br/after/*;

**Comment by mevdschee** [comment]
location ~ \.php$ {

Should be:

    location ~ [^/]\.php(/|$) {

As specified in: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by luisrock** [comment]
Ok, I made the change and now I am getting "Access denied."...

**Comment by mevdschee** [comment]
The OpenAPI specification is served on the "/openapi" endpoint as described in the README:

https://github.com/mevdschee/php-crud-api#openapi-specification

I hope that resolves the issues.

**Comment by luisrock** [comment]
It doesn't, sorry.

Getting "access denied" whenever a put slash after api.php.

https://zeraapi.com.br/api.php/
https://zeraapi.com.br/api.php/openapi
https://zeraapi.com.br/api.php/records/as_users
https://zeraapi.com.br/api.php/anything-here

All "access denied"...

**Comment by mevdschee** [comment]
I'm sorry, but I can't help you if you insist on running a clearly wrong config and are not willing to try the recommended configuration of php-fpm by nginx as specified at: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by luisrock** [comment]
I don't blame you. Helping a rookie is hard...

Well, you say I am "running a clearly wrong config", but that is exactly what I got from Laravel Forge. I have reached them as well with this issue, but they said they would not help me run this script and that I should look for the author's help.

"We don't know how this script works, you'll need to check with the author on what changes are needed on your server for it to work."

When I moved from

`location ~ \.php$ {`

to

`location ~ [^/]\.php(/|$) {`

and got a "access denied", I reached them again, to read in response:

"Please revert your changes."

But, anyway, thanks for being so cooperative. We cannot say we didn't try, right?

Looking forward to trying mintyPHP. My eyes shine when I read "easy to learn"...

Regards

**Comment by mevdschee** [comment]
It is really hard for me to debug your Laravel Forge issue over Github issues. Is there any way I can run your Laravel Forge config locally? Are there configs open source?

**Comment by mevdschee** [comment]
Apparently you can invite me in a "ring" and then add my ssh key to your server. If you do that, then I can debug your problem for you. If you want this, then please send me an email at: maurits@vdschee.nl

**Comment by mevdschee** [comment]
I'm closing the unsupported "year" issue, as this is resolved. Please open a new one if you need further assistance with Nginx.

**Comment by luisrock** [comment]
Hi, man. I would like to give it another try. The offer to help me debug the issue is still on? I can add your ssh key to my server.

**Comment by mevdschee** [comment]
hey @luisrock, I'm happy to help you.. I've sent you an email.. maybe we can continue the conversation on a video call or chat..
