### ISSUE TITLE
Slim v4 integration issue

### ISSUE THREAD

**Issue by kdoe13** [mevdschee/php-crud-api#578]
@mevdschee I started upgrading my project to Slim v4 and I'm getting the same issue that i had here: https://github.com/mevdschee/php-crud-api/issues/567

I'm implementing the CRUD as middleware, but Psr\Http\Message\ServerRequestInterface outputs $request->getParsedBody() as an array, not an object in this version as well. 

So I feel like I need that same workaround as you did for version 3...?

Here is what my Middleware looks like:

use \Psr\Http\Server\MiddlewareInterface;
use \Psr\Http\Message\ServerRequestInterface;
use \Psr\Http\Server\RequestHandlerInterface;
use \Psr\Http\Message\ResponseInterface;
use \Tqdev\PhpCrudApi\Config;
use \Tqdev\PhpCrudApi\Api;
/**
 * Class Crud Request
 *
 * Middleware for sending a request to the php_crud_api if the route
 * was not setup in the main api
 */
class CrudRequest implements MiddlewareInterface
{
  public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
  {
  }
}

So this ends up not working for me on line 80 in Record/RecordController.php where the output of $record is an array instead of an object.

**Comment by mevdschee** [comment]
Can you provide the json you are sending?

**Comment by mevdschee** [comment]
I've tried to reproduce, but I can't. Do you use some middleware that calls `withParsedBody`?

**Comment by kdoe13** [comment]
Here's my Postman request as curl:
  -H 'Content-Type: application/json' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -d '{"lifespan":12, "url":"66sjtest.com", "users_id":41}'

I removed all other middleware between my slim instance and my CRUD middleware.

So my app looks like:
$app = Slim\Factory\AppFactory::create();
$app->add(new Middleware\CrudRequest());
$app->run();

**Comment by mevdschee** [comment]
Okay, so SlimPHP 4 allows for multiple implementations for the ServerRequest Creator

- Slim PSR-7
- Nyholm PSR-7
- Guzzle PSR-7
- Zend Diactoros

see this link: https://www.slimframework.com/2019/08/01/slim-4.0.0-release.html

The one from Slim4 is broken. It does not parse as a PHP object on the parsed body in case of an json object, it is always a PHP array. This was also broken in Slim3 and therefor they have probably kept it broken (for backwards compatibility). But in Slim4 you can simply use a better one (such as Nyholm).

Nevertheless I listed the faulty Slim4 implementation also for re-parsing, just as I did with the Slim3 implementation. Usage is still not recommended though.. (due to computational overhead).

**Comment by mevdschee** [comment]
Release v2.5.3 has been made with this fix in it.

**Comment by mevdschee** [comment]
For reference, read: https://tqdev.com/2019-automatic-rest-api-slimphp-4-minimal

**Comment by kdoe13** [comment]
@mevdschee Thanks for the update. Further issue....I'd like to use https://github.com/slimphp/Slim-Http if possible, b/c I like to use the decorator for returning JSON response ->withJSON...but if I add it as dependency when I process my CRUD middleware with Slim 4, my request is an instance of Slim\Http\ServerRequest instead of Nyholm\Psr7\ServerRequest. Slim\Http works well through the rest of my app, as I can call ->getParsedBody() and ->withJSON, etc...but Nyholm\Psr7 does not support that out of the box as far as I can tell. 

Once I pass the request to the Config.php if I'm using Slim\Http...the CRUD loses my request body information.  I know you continue to use Nyholm\Psr7...so how does your code enable ->getParsedBody()? Or is it possible for CRUD to work with Slim\Http?

**Comment by mevdschee** [comment]
>Once I pass the request to the Config.php if I'm using Slim\Http...the CRUD loses my request body information.

Did you test with v2.5.3? Can you explain what is going wrong?

**Comment by kdoe13** [comment]
Yes I'm fully updated on all my dependencies as far as I can tell. 

So currently, my composer.json looks like this:
```  
 "require": {
        "slim/slim": "^4.2",
        "mevdschee/php-crud-api": "^2.5",
        "slim/http": "^0.8.0"
     }
```
My request to my Slim App is thus: 
```
POST /records/tester HTTP/1.1
Content-Type: application/json
{"lifespan":12, "data":"testData"}
```
I call My CRUD Middleware thus: 
```
use \Psr\Http\Server\MiddlewareInterface;
use \Psr\Http\Message\ServerRequestInterface;
use \Psr\Http\Server\RequestHandlerInterface;
use \Psr\Http\Message\ResponseInterface;
use \Tqdev\PhpCrudApi\Config;
use \Tqdev\PhpCrudApi\Api;

class CrudRequest implements MiddlewareInterface
{
  public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
  {

      var_dump($request);
      var_dump($request->getParsedBody());

      $config = new Config([
      'address'  => getenv('DB_HOST'),
      'username' => getenv('DB_USER'),
      'password' => getenv('DB_PASS'),
      'database' => getenv('DB_NAME'),
      'basePath' => '/',
      'middlewares' => 'authorization, cors, customization',
      'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
        
        var_dump($request);  
        var_dump($request->getParsedBody());
     
     }
  }
}
```

My output in Postman is thus:
```
object(Slim\Http\ServerRequest)#165 (2) {
["serverRequest":protected]=>
   object(Nyholm\Psr7\ServerRequest)#164 (13) {
   }
}
```
```
array(3) {
["lifespan"]=>
int(12)
["data"]=>
string(8) "testData"
}
```
```
object(Slim\Http\ServerRequest)#293 (2) {
["serverRequest":protected]=>
    object(Nyholm\Psr7\ServerRequest)#164 (13) {
    }
}
```
```
NULL
```

**Comment by mevdschee** [comment]
I released a new version. Can you test it?

**Comment by kdoe13** [comment]
When I run the same test as above, I'm still getting NULL on the var_dump of $request->getParsedBody(). 

So when I check at [line 200](https://github.com/mevdschee/php-crud-api/blob/b9b060b8f72dac4506d800f93095fa732456b571/src/Tqdev/PhpCrudApi/Api.php#L200) what the Request body looks like it is an empty string when I have Slim\Http enabled...so it seems like the Body has already been lost before we even get the ApplySlimHack function.

I hope I'm not being a bother, I love your application and I can always just not use the Slim\Http decorators and it wouldn't be the end of the world.

**Comment by mevdschee** [comment]
I'm trying to reproduce your case.. Can you review my code? See:

https://github.com/mevdschee/slim-crud-api/tree/issue-578

I don't get a NULL as you get, but I do use the same 'Slim\Http\ServerRequest'.

**Comment by kdoe13** [comment]
When I work with your repo, the first [var_dump($request) on line 15](https://github.com/mevdschee/slim-crud-api/blob/issue-578/middleware.php#L15) outputs a Nyholm\Psr7\ServerRequest Object, not a Slim\Http\ServerRequest as was happening with my instance. 

I created a repo off of your repo that does not change too much but just moves the index.php to a public folder and adds an .htaccess file...and now that same line on middleware.php (Line 15)...outputs Slim\Http\ServerRequest.  So maybe that is an apache thing that is happening there?

https://github.com/axiomllc/crud-test

**Comment by mevdschee** [comment]
I did this:

    git clone git@github.com:axiomllc/crud-test.git
    cd crud-test/
    wget https://getcomposer.org/composer.phar
    php composer.phar install
    php -S localhost:8080 -t public
    curl -H 'Content-Type: application/json' -d '{"lifespan":12, "data":"testData"}' localhost:8080/records/posts

Output:

    array(2) {
      ["lifespan"]=>
      int(12)
      ["data"]=>
      string(8) "testData"
    }

Is your output different?

**Comment by mevdschee** [comment]
I changed line 15 to:

    var_dump(get_class($request));

And it ouputs:

    string(23) "Slim\Http\ServerRequest"

What am I doing wrong here?

**Comment by mevdschee** [comment]
For comparison:

    maurits@maurits-desktop:~/projects/crud-test$ php composer.phar install
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 12 installs, 0 updates, 0 removals
    - Installing psr/http-message (1.0.1): Loading from cache
    - Installing psr/http-factory (1.0.1): Loading from cache
    - Installing slim/http (0.8): Loading from cache
    - Installing nyholm/psr7-server (0.3.0): Loading from cache
    - Installing php-http/message-factory (v1.0.2): Loading from cache
    - Installing nyholm/psr7 (1.2.1): Loading from cache
    - Installing psr/http-server-handler (1.0.1): Loading from cache
    - Installing psr/http-server-middleware (1.0.1): Loading from cache
    - Installing mevdschee/php-crud-api (v2.5.5): Loading from cache
    - Installing psr/container (1.0.0): Loading from cache
    - Installing nikic/fast-route (v1.3.0): Loading from cache
    - Installing slim/slim (4.2.0): Loading from cache
    slim/slim suggests installing slim/psr7 (Slim PSR-7 implementation. See http://www.slimframework.com/docs/v4/start/installation.html for more information.)
    Writing lock file
    Generating autoload files
    maurits@maurits-desktop:~/projects/crud-test$ 

Do you have the same versions?

**Comment by mevdschee** [comment]
I was eventually able to add the slim/psr7 dependency and reproduce the null that you get. Unfortunately your assumption that an empty parsedbody is a problem is incorrect and is not a problem of and for the script. The body is still in getBody getContents and is not lost.

I hope this helps you.

**Comment by kdoe13** [comment]
hmm, ya I'm still not getting it to work. Your simple slim-crud version branch actually does not work for me either, I had accidentally run composer install from master which didn't include slim/http.

Here are my version stuff...not sure why I get the errors I get on your stuff:
```
Karls-MacBook-Air:another kdoe$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing slim/http (0.8): Loading from cache
  - Installing nyholm/psr7-server (0.3.0): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing nyholm/psr7 (1.2.1): Loading from cache
  - Installing psr/http-server-handler (1.0.1): Loading from cache
  - Installing psr/http-server-middleware (1.0.1): Loading from cache
  - Installing mevdschee/php-crud-api (v2.5.5): Loading from cache
    Failed to execute unzip -qq  '/Users/kdoe/Documents/htdocs/another/vendor/mevdschee/php-crud-api/96aafd4d90c7161f715888b97a26221c' -d '/Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48'

error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/062_read_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/063_list_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/064_add_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/065_edit_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/066_delete_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/073_multi_tenancy_kunsth+?ndv+?rk.log
        Illegal byte sequence
error:  cannot create /Users/kdoe/Documents/htdocs/another/vendor/composer/65358f48/mevdschee-php-crud-api-b9b060b/tests/functional/001_records/074_custom_kunsth+?ndv+?rk.log
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
  - Installing psr/container (1.0.0): Loading from cache
  - Installing nikic/fast-route (v1.3.0): Loading from cache
  - Installing slim/slim (4.2.0): Loading from cache
mevdschee/php-crud-api suggests installing ext-memcache (*)
mevdschee/php-crud-api suggests installing ext-memcached (*)
mevdschee/php-crud-api suggests installing ext-redis (*)
slim/slim suggests installing slim/psr7 (Slim PSR-7 implementation. See http://www.slimframework.com/docs/v4/start/installation.html for more information.)
Writing lock file
Generating autoload files
Karls-MacBook-Air:another kdoe$ 
```

PHP 7.2.1
```
Karls-MacBook-Air:another kdoe$ php -v
PHP 7.2.1 (cli) (built: Jan 15 2018 12:20:50) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

I'm using MAMP PRO to create my apache server (v4.5)

**Comment by mevdschee** [comment]
Can you delete the vendor directory entirely and reinstall dependencies using composer?

**Comment by kdoe13** [comment]
It is still not working for me, but I do have everything working with the following dependencies:
```
    "require": {
        "slim/slim": "^4.2",
        "mevdschee/php-crud-api": "^2.5",
        "slim/psr7": "^0.5.0",
        "slim/http": "^0.8.0"
    }
```

So I am likely to just continue my project from here. I am up for working with you more if you'd like to see if we can figure out what in my settings is making this break but overall I'm happy to move on, as I do have my application working the way I'm expecting it to.

**Comment by kdoe13** [comment]
Any ideas why I'm getting those "Illegal byte sequence" errors? I did clear cache and install fresh.

**Comment by mevdschee** [comment]
>Any ideas why I'm getting those "Illegal byte sequence" errors? I did clear cache and install fresh.

Yes, I can remove those in the next version (utf8 filenames).

**Comment by kdoe13** [comment]
Cool, it isn't an issue, just wanted to make sure they weren't a problem, which it seemed like they were not.

**Comment by mevdschee** [comment]
I released v2.5.6: remove utf8 filenames

**Comment by mevdschee** [comment]
>It is still not working for me, but I do have everything working with the following dependencies:

So what is still not working for you?

**Comment by kdoe13** [comment]
Everything is working, just in order to use slim/http, I also need to use slim/psr7.

**Comment by mevdschee** [comment]
>in order to use slim/http, I also need to use slim/psr7.

Isn't that what is written in the manual? It allows you to chose the psr7 implementation, see:

https://www.slimframework.com/2019/08/01/slim-4.0.0-release.html#step-3-install-a-psr-7-implementation-and-serverrequest-creator

**Comment by mevdschee** [comment]
Since you got it working and it seems that requiring `slim/psr7` is the documented way of enabling Slims's PSR 7 implementation, I think we can close the issue, right?

**Comment by kdoe13** [comment]
But since the crud already uses nyholm...and I like that nyholm is pretty scaled down, I had hoped to be able to use it as my PSR7 implementation with the App as in that documentation..but Nyholm and slim/http do not seem to play nice with the CRUD, at least with my way of doing things, even though it seemed like it was working for you in that simple-crud-api...ya?

**Comment by mevdschee** [comment]
>even though it seemed like it was working for you in that slim-crud-api

Yes indeed, I could not find an issue with it.

**Comment by kdoe13** [comment]
ya so what I was saying is that Nyholm Slim/Http combo isn't working for me, and I'd be up for continuing to figure out why if that would be helpful for you, but if not, my Slim/Psr7 Slim/Http combo is working fully for my application.

**Comment by mevdschee** [comment]
Without the `BodyParsingMiddleware` Slim 4 will not parse the body. See:

https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/BodyParsingMiddleware.php

I hope this clears things up for you.

**Comment by kdoe13** [comment]
That's really not the problem I was having, mainly when I only had Nyholm and Slim\Http, the crud was losing the body for me, not Slim 4. I know you weren't having this issue though, so tough to say if its really a problem or just something I was doing incorrectly.

**Comment by mevdschee** [comment]
I've releaed v2.5.7 that rewinds the body before it reads it in case the body is not yet parsed. This is the only scenario I can think of in which that NULL would appear. Can you test it?

**Comment by mevdschee** [comment]
I'm closing this for now.. feel free to open a new issue if/when you are able to reproduce and/or run into new problems. You have helped a lot to improve the software. Thank you very much for your contribution.

**Comment by kdoe13** [comment]
I've tested it and still no dice, I'm sorry. It seems so strange that it is working for you but not for me. I've tested it on my staging server too and it still doesn't work there.  

I don't quite understand how the crud can drill down into the request object without also having slim/http in your dependency.  On my local machine with your test project https://github.com/mevdschee/slim-crud-api/tree/issue-578, if I output the request object on line 208 (handle function) of the Api.php file...I get the following: 
```
object(Slim\Http\ServerRequest)#47 (2) {
["serverRequest":protected]=>
object(Nyholm\Psr7\ServerRequest)#46 (13) {
}
}
```
Since that serverRequest object is protected and without the dependency loaded, it seems like it would be blocking us from accessing the Nyholm object contained within...which is what is happening on my project. I feel like it's odd that it is working for you....but I don't know what to say about it otherwise.

**Comment by kdoe13** [comment]
I guess the above is somewhat of a stupid comment in retrospect of remembering that slim/psr7 & slim/http, work fine with the crud...but it is how it felt.  

But yes in retrospect...it is so strange, that on the simple-crud-slim setup, the following object works but the one above does not...
```
object(Slim\Http\ServerRequest)#44 (2) {
["serverRequest":protected]=>
object(Slim\Psr7\Request)#42 (12) {
}
}
```

**Comment by mevdschee** [comment]
>Since that serverRequest object is protected and without the dependency loaded, it seems like it would be blocking us from accessing the Nyholm object contained within...which is what is happening on my project.

I feel this is not the right conclusion.

>I feel like it's odd that it is working for you....

I need to be able to reproduce what is not working for you, but I can't.

**Comment by kdoe13** [comment]
> I need to be able to reproduce what is not working for you, but I can't.
> 
> It would be great if you could reproduce your problem on: https://github.com/axiomllc/crud-test

So what is currently in that repo, returns an empty [$body->getContents on line 27
](https://github.com/axiomllc/crud-test/blob/master/middleware.php#L27) as it is currently written and when I implement it both in my MAMP setup local machine as well as my staging shared hosting server. When I dig further into the code on line 208 of Tqdev\PhpCrudApi\Api.php...the request also returns me Null on the body when I have the Slim\Http decorator with Nyholm\Psr7.

**Comment by mevdschee** [comment]
>So what is currently in that repo, returns an empty $body->getContents on line 27

You need to call $body->rewind() before getting the contents (see my PR).

>the request also returns me Null on the body when I have the Slim\Http decorator with Nyholm\Psr7

I can only reproduce this when doing a GET request.
